### ISSUE TITLE
Update stack

### ISSUE THREAD

**Issue by AlexWayfer** [Richard87/releaser#10]
Hi!

I want to make some PRs, but cannot run `ng serve` on my machine :sweat: 

```
$ ng serve
The "@angular/compiler-cli" package was not properly installed.
Error: The "@angular/compiler-cli" package was not properly installed.
    at Object.<anonymous> (/home/alex/Projects/releaser/node_modules/@ngtools/webpack/src/index.js:14:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/alex/Projects/releaser/node_modules/@angular/cli/tasks/eject.js:10:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

Please, update the `package.json` (replace `angular-cli` beta-version for stable `@angular/cli`, for example).

Thanks.

**Comment by Richard87** [comment]
Hi! Justs upgraded everything to ng4 :)

**Comment by AlexWayfer** [comment]
Yay! Thank you!

**Comment by Richard87** [comment]
No problem! Looking forward to what you make with it!
